version: 2.1

orbs:
  php: circleci/php@1.1.0

jobs:
  hosting_website:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - php/install-php:
          version: "7.3"
      - run:
          name: indexページ へのリクエストが正しく返ってくることを確認する
          command: |
            /usr/bin/nohup /usr/bin/php -S localhost:4000 > /tmp/php_built_in_server.log 2>&1 &

            # ビルトインサーバが起動するのを待つ
            until : > /dev/tcp/localhost/4000; do
              echo -n .
              sleep 1
            done
            echo "PHP のビルトインサーバが起動されたことを確認しました"

            # とりあえず index.php へアクセスするだけ
            curl http://localhost:4000

workflows:
  main_workflow:
    jobs:
      - hosting_website
