name: Docker Build Test and Deploy to Cloud Run

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  workflow_dispatch:

env:
  # TODO: Git のタグを取得して、イメージのタグにする
  DOCKER_IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.CLOUD_RUN_PROJECT }}/cloud-run-source-deploy/${{ secrets.CLOUD_RUN_SERVICE_NAME }}
  GCP_REGION: ${{ secrets.CLOUD_RUN_REGION }}

jobs:
  docker_test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v5
    - name: Docker Build & Run (Background)
      run: docker compose up -d
    - name: curl で正しいレスポンスが返ってくること
      run: docker compose exec -T web curl -I http://localhost:80

  deploy_to_cloud_run:
    needs: docker_test
    if: ${{ github.ref_name == 'main' }}
    name: Cloud Run にデプロイする
    runs-on: ubuntu-latest
    steps:
      - name: ソースコードをチェックアウトする
        uses: actions/checkout@v5
      - name: GCP の認証を行う
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: GCP の CLI の認証を行う
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      - name: Docker イメージ をビルドする
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
      - name: Docker イメージ をプッシュする
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
          image: ${{ env.DOCKER_IMAGE }}
          region: ${{ env.GCP_REGION }}
