name: Docker CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  docker_test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    steps:
    - name: コードをチェックアウトする
      uses: actions/checkout@v3
    - name: Docker Build & Run (Background)
      run: docker compose up -d
    - name: curl で正しいレスポンスが返ってくること
      run: docker compose exec -T web curl -I http://localhost:80
